# coding=utf-8
# *** WARNING: this file was generated by pulumi-language-python. ***
# *** Do not edit by hand unless you're certain you know what you are doing! ***

from . import _utilities
import typing
# Export this package's modules as members:
from .provider import *

# Make subpackages available:
if typing.TYPE_CHECKING:
    import pulumi_fcknat.gateway as __gateway
    gateway = __gateway
else:
    gateway = _utilities.lazy_import('pulumi_fcknat.gateway')

_utilities.register(
    resource_modules="""
[
 {
  "pkg": "fcknat",
  "mod": "Gateway",
  "fqn": "pulumi_fcknat.gateway",
  "classes": {
   "fcknat:Gateway:FckNat": "FckNat"
  }
 }
]
""",
    resource_packages="""
[
 {
  "pkg": "fcknat",
  "token": "pulumi:providers:fcknat",
  "fqn": "pulumi_fcknat",
  "class": "Provider"
 }
]
"""
)
