// *** WARNING: this file was generated by pulumi-language-nodejs. ***
// *** Do not edit by hand unless you're certain you know what you are doing! ***

import * as pulumi from "@pulumi/pulumi";
import * as utilities from "../utilities";

// Export members:
export { FckNatArgs } from "./fckNat";
export type FckNat = import("./fckNat").FckNat;
export const FckNat: typeof import("./fckNat").FckNat = null as any;
utilities.lazyLoad(exports, ["FckNat"], () => require("./fckNat"));


const _module = {
    version: utilities.getVersion(),
    construct: (name: string, type: string, urn: string): pulumi.Resource => {
        switch (type) {
            case "fcknat:Gateway:FckNat":
                return new FckNat(name, <any>undefined, { urn })
            default:
                throw new Error(`unknown resource type ${type}`);
        }
    },
};
pulumi.runtime.registerResourceModule("fcknat", "Gateway", _module)
