name: Makefile

on:
  workflow_dispatch:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main
  schedule:
    - cron: "0 0 * * *"

jobs:
  build:
    runs-on: ubuntu-latest
    container:
      image: docker://ghcr.io/pulumi/devcontainer:latest
      options: --user root
    permissions:
      contents: read
      packages: read
      actions: read
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        id: git
        with:
          submodules: "recursive"
      - name: Unshallow clone for tags
        id: tags
        run: |
          sudo chown -R $(whoami) /__w/pulumi-fcknat/pulumi-fcknat
          git config --global --add safe.directory /__w/pulumi-fcknat/pulumi-fcknat
          git fetch --prune --unshallow --tags
      - name: Setup tools
        uses: ./.github/actions/setup-tools
        with:
          tools: go, pulumicli, pulumictl, nodejs, python, dotnet
      - name: Build
        id: build
        run: |
          make build
      - name: Install
        id: install
        run: |
          set -ex
          make install
      - name: Skip PulumiUp (requires AWS credentials)
        id: up
        run: |
          echo "Skipping actual deployment as it requires AWS credentials"
          cd examples/yaml
          export PULUMI_CONFIG_PASSPHRASE=asdfqwerty1234
          pulumi login --local
          # Set mock AWS credentials for preview
          export AWS_ACCESS_KEY_ID=mock-key
          export AWS_SECRET_ACCESS_KEY=mock-secret
          export AWS_REGION=us-east-1
          pulumi stack init test
          pulumi stack select test
          # Preview only - don't try to deploy
          pulumi preview || true
      - name: Skip PulumiDown (not deployed)
        id: down
        run: |
          echo "Nothing to tear down (preview only)"
      - name: Generate multi-language examples from yaml IaC program
        id: examples
        run: |
          set -ex
          make gen_examples
